name = "TrajectoryLimiters"
uuid = "9792e600-fe43-4e4e-833b-462f466b8006"
version = "0.1.3"
authors = ["Fredrik Bagge Carlson"]

[deps]

[compat]
julia = "1.11"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
