name = "TrajectoryLimiters"
uuid = "9792e600-fe43-4e4e-833b-462f466b8006"
version = "0.1.1"
authors = ["Fredrik Bagge Carlson"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.16"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
